name: Auto Label Valid Hacktoberfest PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  add-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check validation status
        id: check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const statuses = await github.rest.repos.listCommitStatusesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha
            });

            const validation = statuses.data.find(s => s.context === 'PR Code Validation');
            const isValid = validation && validation.state === 'success';
            core.setOutput('is_valid', isValid ? 'true' : 'false');

            if (isValid) {
              core.notice('✅ Validation passed. Will add labels.');
            } else {
              core.notice('❌ Validation failed. Labels will not be added.');
            }

      - name: Add Hacktoberfest labels
        if: steps.check.outputs.is_valid == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: ['Hacktoberfest', 'Hacktoberfest-accepted']
            });

      - name: Comment success
        if: steps.check.outputs.is_valid == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const message = `
🎉 **Great job @${pr.user.login}!**

✅ Your code passed validation successfully.  
🏷️ Hacktoberfest labels have been added automatically.  
Keep contributing and happy coding! 💖
`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: message
            });

      - name: Comment failure
        if: steps.check.outputs.is_valid != 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const message = `
⚠️ **Hey @$**
