name: Auto Label Hacktoberfest PRs

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add Hacktoberfest labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: ['Hacktoberfest', 'Hacktoberfest-accepted']
            });
