name: Auto-label new issues for Hacktoberfest

on:
  issues:
    types: [opened]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add Hacktoberfest and Good First Issue labels
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: ['Hacktoberfest', 'Good first issue']
            });

            console.log(`✅ Added labels to issue #${issue.number}`);
