name: PR Code Validation and Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **/*.py
            **/*.java
            **/*.cpp
            **/*.c
            **/*.js
            **/*.ts
            **/*.go
            **/*.rs
            **/*.rb
            **/*.php
            **/*.swift
            **/*.kt
            **/*.scala
            **/*.dart
            **/*.hs

      - name: Validate code quality
        id: validation
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Get list of changed files
            const changedFiles = `${{ steps.changed-files.outputs.all_changed_files }}`.split(' ').filter(f => f);
            
            if (changedFiles.length === 0) {
              console.log('No code files changed in this PR');
              core.setOutput('is_valid', 'true');
              core.setOutput('validation_message', 'No code files to validate');
              return;
            }
            
            console.log('Changed files:', changedFiles);
            
            let isValid = true;
            let validationErrors = [];
            
            // Validation rules based on CONTRIBUTING.md
            for (const file of changedFiles) {
              if (!file) continue;
              
              console.log(`\nValidating: ${file}`);
              
              try {
                const content = fs.readFileSync(file, 'utf8');
                const lines = content.split('\n');
                
                // Check 1: File should not be empty
                if (content.trim().length === 0) {
                  validationErrors.push(`❌ ${file}: File is empty`);
                  isValid = false;
                  continue;
                }
                
                // Check 2: Should have comments/documentation
                const hasComments = content.includes('//') || content.includes('/*') || 
                                   content.includes('"""') || content.includes('#') ||
                                   content.includes('<!--');
                if (!hasComments) {
                  validationErrors.push(`❌ ${file}: Missing documentation/comments`);
                  isValid = false;
                }
                
                // Check 3: Should mention complexity (Time/Space)
                const hasComplexity = /time complexity|space complexity|O\([^)]+\)/i.test(content);
                if (!hasComplexity) {
                  validationErrors.push(`❌ ${file}: Missing time/space complexity analysis`);
                  isValid = false;
                }
                
                // Check 4: Should have some form of example/test/main function
                const hasExample = /main|test|example|if __name__|console\.log|System\.out|println|print\(/i.test(content);
                if (!hasExample) {
                  validationErrors.push(`❌ ${file}: Missing example usage or test cases`);
                  isValid = false;
                }
                
                // Check 5: Basic syntax validation
                // Check for common syntax errors
                const ext = path.extname(file);
                
                // Python: Check for basic syntax
                if (ext === '.py') {
                  // Check for unmatched parentheses/brackets
                  const openParen = (content.match(/\(/g) || []).length;
                  const closeParen = (content.match(/\)/g) || []).length;
                  const openBracket = (content.match(/\[/g) || []).length;
                  const closeBracket = (content.match(/\]/g) || []).length;
                  const openBrace = (content.match(/\{/g) || []).length;
                  const closeBrace = (content.match(/\}/g) || []).length;
                  
                  if (openParen !== closeParen || openBracket !== closeBracket || openBrace !== closeBrace) {
                    validationErrors.push(`❌ ${file}: Potential syntax error - unmatched brackets/parentheses`);
                    isValid = false;
                  }
                }
                
                // Java/C++/C: Check for basic structure
                if (['.java', '.cpp', '.c'].includes(ext)) {
                  const openBrace = (content.match(/\{/g) || []).length;
                  const closeBrace = (content.match(/\}/g) || []).length;
                  
                  if (openBrace !== closeBrace) {
                    validationErrors.push(`❌ ${file}: Potential syntax error - unmatched braces`);
                    isValid = false;
                  }
                  
                  // Java should have class definition
                  if (ext === '.java' && !/(public|private|protected)?\s*(class|interface)\s+\w+/i.test(content)) {
                    validationErrors.push(`❌ ${file}: Missing class definition`);
                    isValid = false;
                  }
                }
                
                // Check 6: No obvious spam patterns
                const spamPatterns = [
                  /^[\s\n]*$/,  // Only whitespace
                  /lorem ipsum/i,
                  /test test test/i,
                  /asdf|qwerty|12345/
                ];
                
                for (const pattern of spamPatterns) {
                  if (pattern.test(content) && content.length < 100) {
                    validationErrors.push(`❌ ${file}: Appears to be spam or meaningless content`);
                    isValid = false;
                    break;
                  }
                }
                
                // Check 7: File should have meaningful content (more than just imports/includes)
                const meaningfulLines = lines.filter(line => {
                  const trimmed = line.trim();
                  return trimmed.length > 0 && 
                         !trimmed.startsWith('import ') &&
                         !trimmed.startsWith('from ') &&
                         !trimmed.startsWith('#include') &&
                         !trimmed.startsWith('//') &&
                         !trimmed.startsWith('/*') &&
                         !trimmed.startsWith('*') &&
                         !trimmed.startsWith('#');
                }).length;
                
                if (meaningfulLines < 10) {
                  validationErrors.push(`❌ ${file}: File has insufficient meaningful content (< 10 lines)`);
                  isValid = false;
                }
                
                if (isValid) {
                  console.log(`✅ ${file}: Passed validation`);
                }
                
              } catch (error) {
                console.error(`Error reading ${file}:`, error.message);
                validationErrors.push(`❌ ${file}: Could not read file - ${error.message}`);
                isValid = false;
              }
            }
            
            // Set outputs
            core.setOutput('is_valid', isValid ? 'true' : 'false');
            
            if (isValid) {
              core.setOutput('validation_message', '✅ All code quality checks passed!');
            } else {
              const errorMessage = 'Code validation failed:\n\n' + validationErrors.join('\n');
              core.setOutput('validation_message', errorMessage);
            }
            
            return isValid;

      - name: Add labels and approve if valid
        if: steps.validation.outputs.is_valid == 'true'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.GH_PAT }}
          script: |
            const pr = context.payload.pull_request;
            
            // Add Hacktoberfest labels
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['Hacktoberfest', 'Hacktoberfest-accepted']
              });
              console.log('✅ Added Hacktoberfest labels');
            } catch (error) {
              console.log('Note: Labels may not exist. Error:', error.message);
            }
            
            // Approve the PR
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              event: 'APPROVE',
              body: '✅ Code validation passed! This PR meets all quality standards:\n\n' +
                    '- ✅ Has proper documentation/comments\n' +
                    '- ✅ Includes time/space complexity analysis\n' +
                    '- ✅ Contains example usage or test cases\n' +
                    '- ✅ Passes basic syntax validation\n' +
                    '- ✅ Has meaningful content\n\n' +
                    'Approved for merge! 🎉'
            });
            console.log('✅ PR approved');

      - name: Auto-merge PR if valid
        if: steps.validation.outputs.is_valid == 'true'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.GH_PAT }}
          script: |
            const pr = context.payload.pull_request;
            
            try {
              // Enable auto-merge
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash',
                commit_title: `${pr.title} (#${pr.number})`,
                commit_message: `Automatically merged after passing code validation checks.\n\n${pr.body || ''}`
              });
              console.log('✅ PR merged successfully');
            } catch (error) {
              console.log('Could not auto-merge PR:', error.message);
              console.log('PR may require additional approvals or have merge conflicts');
            }

      - name: Request changes if invalid
        if: steps.validation.outputs.is_valid == 'false'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.GH_PAT }}
          script: |
            const pr = context.payload.pull_request;
            const validationMessage = `${{ steps.validation.outputs.validation_message }}`;
            
            // Comment on the PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: '## ❌ Your code is incorrect\n\n' +
                    'Your PR does not meet the quality standards outlined in CONTRIBUTING.md.\n\n' +
                    '### Issues Found:\n\n' +
                    validationMessage + '\n\n' +
                    '### Next Steps:\n\n' +
                    '1. Review the [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) guidelines\n' +
                    '2. Check the [TEMPLATE.md](../blob/main/TEMPLATE.md) for code structure\n' +
                    '3. Fix the issues listed above\n' +
                    '4. Push your changes to update this PR\n\n' +
                    'The validation will run again automatically when you update your PR. 🔄'
            });
            
            // Request changes
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              event: 'REQUEST_CHANGES',
              body: '❌ Code validation failed. Please address the issues mentioned in the comment above.'
            });
            
            console.log('✅ Requested changes on PR');
