name: PR Code Validation and Auto-label

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write

jobs:
  validate-and-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **/*.py
            **/*.java
            **/*.cpp
            **/*.c
            **/*.js
            **/*.ts
            **/*.go
            **/*.rs
            **/*.rb
            **/*.php
            **/*.swift
            **/*.kt
            **/*.scala
            **/*.dart
            **/*.hs

      - name: Validate code quality
        id: validation
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # or use PAT for forks
          script: |
            const fs = require('fs');
            const path = require('path');
            const changedFiles = `${{ steps.changed-files.outputs.all_changed_files }}`.split(' ').filter(f => f);
            let isValid = true;

            if (changedFiles.length === 0) {
              core.setOutput('is_valid', 'true');
              return;
            }

            for (const file of changedFiles) {
              const content = fs.readFileSync(file, 'utf8');
              if (content.trim().length === 0) isValid = false;
            }

            core.setOutput('is_valid', isValid ? 'true' : 'false');

      - name: Add Hacktoberfest labels
        if: steps.validation.outputs.is_valid == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # use PAT if labeling fork PRs
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: ['Hacktoberfest', 'Hacktoberfest-accepted']
            });
